gui:
    scrollPastBottom: false # enable scrolling past the bottom
    showFileTree: true
    sidePanelWidth: 0.25
    language: en
    theme:
        activeBorderColor:
            - blue
            - bold
        inactiveBorderColor:
            - white
        optionsTextColor:
            - blue
        selectedLineBgColor:
            - default
        selectedRangeBgColor:
            - magenta
        cherryPickedCommitBgColor:
            - yellow
        cherryPickedCommitFgColor:
            - magenta
keybinding:
    universal:
        quit: 'q'
        quit-alt1: '<c-c>' # alternative/alias of quit
        return: '<esc>' # return to previous menu, will quit if there's nowhere to return
        quitWithoutChangingDirectory: 'Q'
        togglePanel: '<tab>' # goto the next panel
        prevItem: '<up>' # go one line up
        nextItem: '<down>' # go one line down
        prevItem-alt: 'k' # go one line up
        nextItem-alt: 'j' # go one line down
        prevPage: ',' # go to next page in list
        nextPage: '.' # go to previous page in list
        gotoTop: '<' # go to top of list
        gotoBottom: '>' # go to bottom of list
        prevBlock: '<left>' # goto the previous block / panel
        nextBlock: '<right>' # goto the next block / panel
        prevBlock-alt: 'h' # goto the previous block / panel
        nextBlock-alt: 'l' # goto the next block / panel
        nextMatch: 'n'
        prevMatch: 'N'
        optionMenu: 'x' # show help menu
        optionMenu-alt1: '?' # show help menu
        select: '<space>'
        goInto: '<enter>'
        openRecentRepos: '<c-r>'
        confirm: '<enter>'
        confirm-alt1: 'y'
        remove: 'd'
        new: 'n'
        edit: 'e'
        openFile: 'o'
        scrollUpMain: '<pgup>' # main panel scroll up
        scrollDownMain: '<pgdown>' # main panel scroll down
        scrollUpMain-alt1: 'K' # main panel scroll up
        scrollDownMain-alt1: 'J' # main panel scroll down
        scrollUpMain-alt2: '<c-u>' # main panel scroll up
        scrollDownMain-alt2: '<c-d>' # main panel scroll down
        executeShellCommand: ':'
        createRebaseOptionsMenu: 'm'
        pushFiles: 'p'
        pullFiles: 'P'
        refresh: 'R'
        createPatchOptionsMenu: '<c-p>'
        nextTab: ']'
        prevTab: '['
        nextScreenMode: '+'
        prevScreenMode: '_'
        undo: 'z'
        redo: '<c-z>'
        filteringMenu: '<c-s>'
        diffingMenu: 'W'
        diffingMenu-alt: '<c-e>' # deprecated
        copyToClipboard: '<c-o>'
        submitEditorText: '<enter>'
        appendNewline: '<a-enter>'
        extrasMenu: '@'
        toggleWhitespaceInDiffView: '<c-w>'
    status:
        checkForUpdate: 'u'
        recentRepos: '<enter>'
    files:
        commitChanges: 'c'
        commitChangesWithoutHook: 'w' # commit changes without pre-commit hook
        amendLastCommit: 'A'
        commitChangesWithEditor: 'C'
        ignoreFile: 'i'
        refreshFiles: 'r'
        stashAllChanges: 's'
        viewStashOptions: 'S'
        toggleStagedAll: 'a' # stage/unstage all
        viewResetOptions: 'D'
        fetch: 'f'
        toggleTreeView: '`'
    branches:
        createPullRequest: 'o'
        viewPullRequestOptions: 'O'
        checkoutBranchByName: 'c'
        forceCheckoutBranch: 'F'
        rebaseBranch: 'r'
        mergeIntoCurrentBranch: 'M'
        viewGitFlowOptions: 'i'
        fastForward: 'f' # fast-forward this branch from its upstream
        pushTag: 'P'
        setUpstream: 'u' # set as upstream of checked-out branch
        fetchRemote: 'f'
    commits:
        squashDown: 's'
        renameCommit: 'r'
        renameCommitWithEditor: 'R'
        viewResetOptions: 'g'
        markCommitAsFixup: 'f'
        createFixupCommit: 'F' # create fixup commit for this commit
        squashAboveCommits: 'S'
        moveDownCommit: '<c-j>' # move commit down one
        moveUpCommit: '<c-k>' # move commit up one
        amendToCommit: 'A'
        pickCommit: 'p' # pick commit (when mid-rebase)
        revertCommit: 't'
        cherryPickCopy: 'c'
        cherryPickCopyRange: 'C'
        pasteCommits: 'v'
        tagCommit: 'T'
        checkoutCommit: '<space>'
        resetCherryPick: '<c-R>'
        copyCommitMessageToClipboard: '<c-y>'
    stash:
        popStash: 'g'
    commitFiles:
        checkoutCommitFile: 'c'
    main:
        toggleDragSelect: 'v'
        toggleDragSelect-alt: 'V'
        toggleSelectHunk: 'a'
        pickBothHunks: 'b'
    submodules:
        init: 'i'
        update: 'u'
        bulkMenu: 'b'
git:
    paging:
        colorArg: always
        pager: DELTA_FEATURES='mantis-shrimp-lite no-side-by-side' delta --paging=never
