#!/bin/bash

DIR="${HOME}/.config/polybar/"

if [[ $1 = "light" ]]; then
    COLORS=colors.day
else
    COLORS=colors.night
fi

cp $DIR/forest/$COLORS $DIR/forest/colors.ini
${HOME}/.config/polybar/launch.sh --forest > /dev/null 2>&1 &
