#!/usr/bin/env bash

dir="$HOME/.config/rofi"

themes="$dir/themes"
dracula="$themes/dracula"
sidetext="$themes/sidetext"

cmd="rofi -no-lazy-grab -monitor -1"

case "$1" in
    "")
        theme=$dracula
        show="drun"
        modi="drun"
        ;;
    "Clipboard")
        theme=$dracula
        show="Clip"
        modi="$show:$dir/modi/$1.sh"
        extra='-kb-remove-char-forward Delete -kb-custom-1 Control+d'
        ;;
    "Bluetooth")
        theme=$sidetext
        $dir/modi/$1.sh "$cmd -theme $sidetext -dmenu -p  -i"
        exit 0
        ;;
    "Kill")
        theme=$sidetext
        show="✗"
        modi="$show:$dir/modi/$1.sh"
        ;;
    "Power")
        theme=$sidetext
        show="⏻"
        modi="$show:$dir/modi/$1.sh"
        ;;
    "MPV")
        theme=$sidetext
        show="▶"
        modi="$show:$dir/modi/$1.sh"
        extra='-kb-remove-char-forward Delete -kb-custom-1 Control+d'
        ;;
esac

$cmd -theme $theme -modi "$modi" -show $show $extra
