# -- Autostart (run once on startup) --
# exec-once=swayidle -w \
#   timeout 300 swaylock \
#   timeout 600 'mmsg -d disable_monitor,^eDP-1$' \
#   resume 'mmsg -d enable_monitor,^eDP-1$' \
#   before-sleep swaylock
exec-once=wl-paste --watch cliphist store
exec-once=mako
exec-once=udiskie -t
exec-once=wlsunset -l "-23.536215622740578" -L "-46.68497829306198" -t "3500" -T "6500" -d "1800"
exec-once=foot --server

# -- Exec on every config reload --
exec=~/.local/bin/desktop_setup
