# Dracula theme colors (0xRRGGBBAA)
rootcolor=0x282936ff
bordercolor=0x3a3c4eff
focuscolor=0x62d6e8ff
urgentcolor=0xea51b2ff
dropcolor=0x62648355
splitcolor=0xb45bcfff
maximizescreencolor=0x00f769ff
scratchpadcolor=0x4d4f68ff
globalcolor=0xb45bcfff
overlaycolor=0x62d6e8ff
