# -- Assign apps to tags --
windowrule=tags:3,appid:^wcode$
windowrule=tags:4,title:^Cursor$
windowrule=tags:7,appid:org.telegram.desktop
windowrule=tags:7,appid:Slack
windowrule=tags:7,title:Slack
windowrule=tags:7,title:zoom
windowrule=tags:10,appid:^stig$

# -- Floating windows --
windowrule=isfloating:1,appid:^pginit$
windowrule=isfloating:1,appid:^pgstop$
windowrule=isfloating:1,appid:^htop$
windowrule=isfloating:1,appid:^btop$
windowrule=isfloating:1,appid:^pulsemixer$
windowrule=isfloating:1,appid:^impala$
windowrule=isfloating:1,appid:^bluetui$
windowrule=isfloating:1,appid:^kill$
windowrule=isfloating:1,width:1440,height:810,appid:^com.gabm.satty$
windowrule=isfloating:1,width:1440,height:1080,appid:^calendar$
windowrule=isfloating:1,width:600,height:400,appid:^qalc$
windowrule=isfloating:1,width:600,height:400,appid:^cmd$
windowrule=isfloating:1,width:600,height:400,appid:^scratchpad$

# ---- Scratchpad ----
scratchpad_width_ratio=0.3
scratchpad_height_ratio=0.3
single_scratchpad=1
scratchpad_cross_monitor=0

# ---- Layer Rules ----
layerrule=animation_type_open:zoom,animation_type_close:zoom,layer_name:rofi
