# ---- APPS Mode (SUPER+Space) ----
keymode=APPS
bind=NONE,space,spawn,~/.config/rofi/launch
bind=NONE,Return,spawn,footclient --app-id cmd
bind=NONE,k,spawn,footclient --app-id kill -- fzf_kill
bind=SHIFT,k,spawn,footclient --app-id kill -- fzf_kill SIGKILL
bind=NONE,c,spawn,footclient --app-id calendar -- zsh -i -c "gcal_notifier print m; read -k"
bind=NONE,m,spawn,footclient --app-id qalc -- qalc -t
bind=NONE,v,spawn,footclient --app-id pulsemixer -- pulsemixer
bind=NONE,b,spawn,footclient --app-id bluetui -- bluetui
bind=NONE,n,spawn,footclient --app-id impala -- impala
bind=NONE,h,spawn,footclient --app-id btop -- btop --preset 1
bind=NONE,t,spawn,footclient --app-id scratchpad -- nvim "/tmp/tmp_$(date +%s)"
bind=NONE,p,spawn,~/.config/rofi/launch MPV
bind=NONE,s,setkeymode,SPOTIFY
bind=NONE,backspace,spawn,wlogout -p layer-shell
bind=NONE,Escape,setkeymode,default

# ---- SPOTIFY Mode ----
keymode=SPOTIFY
bind=NONE,i,spawn,~/.local/bin/sptinit
bind=NONE,s,spawn,~/.local/bin/sptstop
bind=NONE,Escape,setkeymode,default
