# ---- Screenshot Mode (SUPER+S) ----
keymode=SCREENSHOT
bind=NONE,s,spawn,/usr/bin/grimshot --notify copy anything
bind=NONE,f,spawn,/usr/bin/grimshot --notify copy output
bind=NONE,a,spawn,/usr/bin/grimshot --notify copy active
bind=SHIFT,s,spawn,wl-paste -t image/png > $HOME/Images/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
bind=SHIFT,a,spawn,wl-paste -t image/png | satty -f -
bind=NONE,Escape,setkeymode,default
