# ---- Work Mode (SUPER+W) ----
keymode=WORK
bind=NONE,s,spawn,~/.local/bin/work_starter
bind=NONE,b,spawn,zen-browser -P 'Upwork'
bind=NONE,n,spawn,zen-browser -P 'Upwork'
bind=NONE,m,spawn,TZ='America/Sao_Paulo' slack
bind=NONE,d,spawn,dbeaver
bind=NONE,c,spawn,footclient --app-id wcode -- zsh -i -c projw
bind=NONE,Escape,setkeymode,default
