#!/bin/bash

if [ $# -eq 0 ]; then

    result=$(cat ~/.sun)
    IFS=" " read -r sunrise sunset <<< "$result"
    now=$(date +%R)

    if [[ "$now" > "$sunrise" ]] && [[ "$now" < "$sunset" ]]; then
        MODE=light
    else
        MODE=dark
    fi
else
    MODE=$1
fi

/home/thales/Scripts/feh_init $MODE &!
/home/thales/Scripts/polybar_starter $MODE &!
