hl.define_submap("APPS", "reset", function()
    hl.bind("SPACE", "exec", CONFIG_DIR .. "/rofi/launch")
    hl.bind("SUPER + SPACE", "exec", CONFIG_DIR .. "/rofi/launch")
    hl.bind("RETURN", "exec", TERMINAL .. " --app-id cmd")
    hl.bind("K", "exec", TERMINAL .. " --app-id kill -- fzf_kill")
    hl.bind("SHIFT + K", "exec", TERMINAL .. " --app-id kill -- fzf_kill SIGKILL")
    hl.bind("C", "exec", TERMINAL .. " --app-id calendar -- " .. OPEN_CALENDAR)
    hl.bind("M", "exec", TERMINAL .. " --app-id qalc -- qalc -t")
    hl.bind("V", "exec", TERMINAL .. " --app-id pulsemixer -- pulsemixer")
    hl.bind("B", "exec", TERMINAL .. " --app-id bluetui -- bluetui")
    hl.bind("N", "exec", TERMINAL .. " --app-id impala -- impala")
    hl.bind("H", "exec", TERMINAL .. " --app-id btop -- btop --preset 1")
    hl.bind("T", "exec", TERMINAL .. " --app-id scratchpad -- nvim '/tmp/tmp_$(date +%s)'")
    hl.bind("P", "exec", CONFIG_DIR .. "/rofi/launch MPV")
    hl.bind("S", hl.dsp.submap("SPOTIFY"))
    hl.bind("BACKSPACE", "exec", "wlogout -p layer-shell")
    hl.bind("ESCAPE", hl.dsp.submap("reset"))
end)

hl.define_submap("SPOTIFY", "reset", function()
    hl.bind("I", "exec", BIN .. "/sptinit")
    hl.bind("S", "exec", BIN .. "/sptstop")
    hl.bind("ESCAPE", hl.dsp.submap("reset"))
end)
