hl.bind("SUPER + H", "movefocus", "l")
hl.bind("SUPER + J", "movefocus", "d")
hl.bind("SUPER + K", "movefocus", "u")
hl.bind("SUPER + L", "movefocus", "r")

hl.bind("SUPER + ALT + H", "movewindow", "l")
hl.bind("SUPER + ALT + J", "movewindow", "d")
hl.bind("SUPER + ALT + K", "movewindow", "u")
hl.bind("SUPER + ALT + L", "movewindow", "r")

hl.bind("SUPER + I", "focusmonitor", "l")
hl.bind("SUPER + O", "focusmonitor", "r")

hl.bind("SUPER + ALT + I", "movecurrenttomonitor", "l")
hl.bind("SUPER + ALT + O", "movecurrenttomonitor", "r")

hl.bind("SUPER + PERIOD", "resizeactive", "5 0")
hl.bind("SUPER + COMMA", "resizeactive", "-5 0")
hl.bind("SUPER + ALT + PERIOD", "resizeactive", "0 5")
hl.bind("SUPER + ALT + COMMA", "resizeactive", "0 -5")

hl.bind("SUPER + 1", "workspace", "1")
hl.bind("SUPER + 2", "workspace", "2")
hl.bind("SUPER + 3", "workspace", "3")
hl.bind("SUPER + 4", "workspace", "4")
hl.bind("SUPER + 5", "workspace", "5")
hl.bind("SUPER + 6", "workspace", "6")
hl.bind("SUPER + 7", "workspace", "7")
hl.bind("SUPER + 8", "workspace", "8")
hl.bind("SUPER + 9", "workspace", "9")
hl.bind("SUPER + 0", "workspace", "10")

hl.bind("SUPER + ALT + 1", "movetoworkspace", "1")
hl.bind("SUPER + ALT + 2", "movetoworkspace", "2")
hl.bind("SUPER + ALT + 3", "movetoworkspace", "3")
hl.bind("SUPER + ALT + 4", "movetoworkspace", "4")
hl.bind("SUPER + ALT + 5", "movetoworkspace", "5")
hl.bind("SUPER + ALT + 6", "movetoworkspace", "6")
hl.bind("SUPER + ALT + 7", "movetoworkspace", "7")
hl.bind("SUPER + ALT + 8", "movetoworkspace", "8")
hl.bind("SUPER + ALT + 9", "movetoworkspace", "9")
hl.bind("SUPER + ALT + 0", "movetoworkspace", "10")

hl.bind("SUPER + F", "fullscreen")
hl.bind("SUPER + TAB", "cyclenext")
hl.bind("SUPER + SHIFT + F", "togglefloating")
hl.bind("SUPER + SHIFT + TAB", "focuscurrentorlast")
hl.bind("SUPER + Q", "killactive")
hl.bind("SUPER + SHIFT + R", "exec", "hyprctl reload")
hl.bind("SUPER + BACKSPACE", "exec", terminal .. " -- tmux_init")
hl.bind("SUPER + ALT + BACKSPACE", "exec", "wlogout -p layer-shell")

hl.bind("SUPER + B", "exec", "zen-browser -P 'Pessoal'")
hl.bind("SUPER + M", "exec", "Telegram")
hl.bind("SUPER + N", "exec", "hyprctl dispatch workspace 9 && zen-browser -P 'Pessoal' --new-window 'web.whatsapp.com'")
hl.bind("SUPER + E", "exec", terminal .. " -- ranger")
hl.bind("SUPER + SHIFT + E", "exec", "pcmanfm")
hl.bind("SUPER + V", "exec", config_dir .. "/rofi/launch Clipboard")

hl.bind("XF86AudioRaiseVolume", "exec", volume_up, { locked = true })
hl.bind("XF86AudioLowerVolume", "exec", volume_down, { locked = true })
hl.bind("XF86AudioMute", "exec", volume_mute, { locked = true })
hl.bind("XF86AudioPlay", "exec", play_pause_toggle, { locked = true })
hl.bind("XF86AudioPause", "exec", play_pause_toggle, { locked = true })
hl.bind("XF86AudioNext", "exec", play_next, { locked = true })
hl.bind("XF86AudioPrev", "exec", play_previous, { locked = true })

hl.bind("XF86MonBrightnessUp", "exec", brightness_up, { locked = true })
hl.bind("XF86MonBrightnessDown", "exec", brightness_down, { locked = true })
hl.bind("ALT + XF86MonBrightnessUp", "exec", brightness_max, { locked = true })
hl.bind("ALT + XF86MonBrightnessDown", "exec", brightness_min, { locked = true })

hl.bind("XF86PowerOff", "exec", suspend)

hl.bind("ALT + SPACE", "exec", close_notification)
hl.bind("ALT + CONTROL, SPACE", "exec", close_all_notifications)
hl.bind("ALT + CONTROL, H", "exec", redisplay_last_notification)

hl.bind("MOD + ALT + DELETE", "exec", lock)

hl.bind("MOD + SPACE", hl.dsp.submap("APPS"))
hl.bind("MOD + S", hl.dsp.submap("SCREENSHOT"))
hl.bind("MOD + W", hl.dsp.submap("WORK"))
