hl.define_submap("WORK", "reset", function()
    hl.bind("S", "exec", bin .. "/work_starter")
    hl.bind("B", "exec", "hyprctl dispatch workspace 2 && zen-browser -P 'Upwork'")
    hl.bind("N", "exec", "hyprctl dispatch workspace 9 && zen-browser -P 'Upwork'")
    hl.bind("M", "exec", "TZ='America/Sao_Paulo' slack")
    hl.bind("D", "exec", "dbeaver")
    hl.bind("C", "exec", terminal .. " --app-id wcode -- zsh -i -c projw")
    hl.bind("ESCAPE", hl.dsp.submap("reset"))
end)
