server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "rofi"
preview_length = 100

[rofi]
line_length = 100
menu_length = 30
menu_prompt = "Clip"
extra_arguments = ["-i", "-no-lazy-grab", "-monitor", "-1", "-theme", "~/.config/rofi/themes/sidetext"]

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Clip"
extra_arguments = []

[choose]
line_length = 100
menu_length = 30
menu_prompt = "Clip"
extra_arguments = []

[custom_finder]
program = "fzf"
args = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
