[ids]
# Match all devices except your ZMK keyboard
# You can find your ZMK ID by running `keyd monitor` and plugging it in.
*
-1d50:615e # ZMK Ergonaut Keyboard

[global]
overload_tap_timeout = 250

[main]
# Caps is Esc when tapped, nav_layer when held
capslock = overload(nav_layer, esc)

[nav_layer]
h = left
j = down
k = up
l = right

s = home
d = pagedown
f = pageup
g = end
