[ids]
# Alter behavior only in internal laptop keyboard
0001:0001

[main]
# Caps is Esc when tapped, nav_layer when held
capslock = overloadt(nav_layer, esc, 250)
esc = capslock

[nav_layer]
h = left
j = down
k = up
l = right

s = home
d = pagedown
f = pageup
g = end
