#!/bin/bash

DIR="/home/thales/Imagens/Wallpapers"
day="cropped-1920-1080-679478.jpg"
night="cropped-1920-1080-959309.png"

if [[ $1 = "light" ]]; then
    Wallpaper=$day
else
    Wallpaper=$night
fi

feh --no-fehbg --bg-fill "$DIR/$Wallpaper"
