hl.window_rule({ match = { app_id = "^pginit$" }, float = true })
hl.window_rule({ match = { app_id = "^pgstop$" }, float = true })
hl.window_rule({ match = { app_id = "^htop$" }, float = true })
hl.window_rule({ match = { app_id = "^btop$" }, float = true })
hl.window_rule({ match = { app_id = "^pulsemixer$" }, float = true })
hl.window_rule({ match = { app_id = "^impala$" }, float = true })
hl.window_rule({ match = { app_id = "^bluetui$" }, float = true })
hl.window_rule({ match = { app_id = "^kill$" }, float = true })
hl.window_rule({ match = { app_id = "^com.gabm.satty$" }, float = true, size = "1440 810" })
hl.window_rule({ match = { app_id = "^calendar$" }, float = true, size = "1440 1080" })
hl.window_rule({ match = { app_id = "^qalc$" }, float = true, size = "600 400", move = "1301 0" })
hl.window_rule({ match = { app_id = "^cmd$" }, float = true, size = "600 400", move = "1301 0" })
hl.window_rule({ match = { app_id = "^scratchpad$" }, float = true, size = "600 400", move = "1301 0" })

hl.window_rule({ match = { app_id = "^wcode$" }, workspace = "3" })
hl.window_rule({ match = { class = "^Cursor$" }, workspace = "4" })
hl.window_rule({ match = { app_id = "org.telegram.desktop" }, workspace = "7" })
hl.window_rule({ match = { class = "Slack" }, workspace = "7" })
hl.window_rule({ match = { app_id = "Slack" }, workspace = "7" })
hl.window_rule({ match = { class = "zoom" }, workspace = "7" })
hl.window_rule({ match = { app_id = "^stig$" }, workspace = "10" })
